/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#undef DOCA_ARCH_ARM

#undef DOCA_ARCH_DPU

#define DOCA_ARCH_HOST

#define DOCA_ARCH_X86

